version: '3.6'
services: 

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"  
    environment: 
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_HTTP_ENABLED: "true"
      INFLUXDB_DB: "plantdb"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: secretpassword
      # - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      # Data persistency
      # sudo mkdir -p ./server/influxdb/data
      - ./server/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:master
    container_name: grafana
    restart: unless-stopped
    user: '472'
    ports:
      - 3000:3000
    # environment: 
    #   - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p ./server/grafana/data; chown 472:472 ./server/grafana/data
      - ./server/grafana:/var/lib/grafana

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
      - mosquitto
    volumes:
      - ./server/telegraf.conf:/etc/telegraf/telegraf.conf

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./server/mosquitto.conf:/mosquitto/config/mosquitto.conf

